name: meal_planner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  cached_network_image: ^3.4.1
  firebase_auth: ^4.16.0
  table_calendar: ^3.0.9
  fluttertoast: ^8.2.2
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
