// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70dy0NNcx-wz-64-Wor3iiJ_u4dML27M',
    appId: '1:1093890131171:android:b4e3c9a5ae1498dc5631d6',
    messagingSenderId: '1093890131171',
    projectId: 'meal-planner-app-b9316',
    databaseURL: 'https://meal-planner-app-b9316-default-rtdb.firebaseio.com',
    storageBucket: 'meal-planner-app-b9316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU0na31h-tMjyRP2JeX2NpXYV0by9nTB0',
    appId: '1:1093890131171:ios:0aae6e571420d4cf5631d6',
    messagingSenderId: '1093890131171',
    projectId: 'meal-planner-app-b9316',
    databaseURL: 'https://meal-planner-app-b9316-default-rtdb.firebaseio.com',
    storageBucket: 'meal-planner-app-b9316.firebasestorage.app',
    iosBundleId: 'com.example.mealPlanner',
  );

}